# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('inpro', 'In Progress'), ('comp', 'Complete')], default=('inpro', 'In Progress'), max_length=200, null=True),
        ),
    ]
