# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20170613_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joining_date',
            field=models.DateField(null=True),
        ),
    ]
